# .cargo/config.toml

[build]
rustflags = ["--cfg", "tokio_unstable"]

# # Linux
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"] # 如果安装了 mold
# # 或者使用 lld: rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# # macOS (Apple Silicon)
# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# # Windows
# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
